baseURL = "https://clearlove1605.github.io/MyBlog/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "All I Know"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-177864357-1"

[params]
title = "Hello Friend"
author = "ClearLove"
description = "ClearLove"
profilePicture = "https://i.imgur.com/h0reF82.png"
keywords = ""
favicon = "https://i.imgur.com/h0reF82.png"
customCss = []
customJs = []
mainSections = ["post"]
images = ["https://i.imgur.com/h0reF82.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/viethung.rng"

[[params.socialIcons]]
icon = "fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/channel/UCWNupkNK4YiO0Y6zbuIT_9Q/playlists"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/clearlove1605/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:viethung.rng@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"